[build]
  command = "npm run build"
  publish = ".next"

[[context.production.plugins]]
package = "/plugins/netlify-check-hpedge-enabled"
  [context.production.plugins.inputs]
    site_name = "mammut.com"